name: my_car_manager
description: MyCarManager - gestione veicoli, scadenze, obblighi, spese e lavori.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  http: ^1.2.1
  flutter_svg: ^2.3.0
  flutter_local_notifications: ^22.3.0
  workmanager: ^0.10.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/ic_launcher_foreground.webp"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.webp"
